name: Sample application deployment
on:
  push:
    tags: [ '*\.*\.*' ]

jobs:   
  build:    
    runs-on: home-runner    
    env:      
      DOCKER_REGISTRY: devkrolikowski
      DOCKER_IMAGE: swiss-army-knife      
      DOCKER_USERNAME: ${{ secrets.DOCKERHUB_LOGIN }}
      DOCKER_PASSWORD: ${{ secrets.DOCKERHUB_LOGIN }}  
      DOCKER_TARGET_PLATFORM: linux/arm/v7                     
    steps:    
    - name: Checkout the code       
      uses: actions/checkout@v1
    - name: Read tags
      id: read
      run: echo "tag=${GITHUB_REF#refs/*/}" >> $GITHUB_OUTPUT
    - name: Check output
      env:
        RELEASE_VERSION: ${{ steps.read.outputs.tag }}
      run: |
        echo tag: ${{ steps.read.outputs.tag }}
    - name: Set up Docker Buildx      
      uses: crazy-max/ghaction-docker-buildx@v1
      with:        
        version: latest        
    - name: Prepare
      if: success()
      id: prepare      
      run: |        
        echo ::set-output name=docker_platform::${DOCKER_TARGET_PLATFORM}        
        echo ::set-output name=docker_image::${DOCKER_REGISTRY}/${DOCKER_IMAGE}        
        echo ::set-output name=version::${GITHUB_RUN_NUMBER}        
    - name: Login to DockerHub
      uses: docker/login-action@v2
      if: ${{ steps.read.outputs.tag }} != 'main'
      with:
        username: ${{ secrets.DOCKERHUB_LOGIN }}
        password: ${{ secrets.DOCKERHUB_PASS }}
    - name: Run Buildx (push image)
      if: success()      
      run: |        
        docker buildx build \
        --platform ${{ steps.prepare.outputs.docker_platform }} \
        --tag ${{ steps.prepare.outputs.docker_image }}:${{ steps.read.outputs.tag }} \
        --file ./Dockerfile \
        --output type=image,push=true .
