name: Sample application deployment
on:
  push:
    tags: [ '*\.*\.*' ]

jobs:
  publish_to_dockerhub:
    runs-on: ubuntu-latest
    steps:
    - name: Chechout code
      uses: actions/checkout@v3
    - name: Read tags
      id: read
      run: echo "tag=${GITHUB_REF#refs/*/}" >> $GITHUB_OUTPUT
    - name: Check output
      env:
        RELEASE_VERSION: ${{ steps.read.outputs.tag }}
      run: |
        echo tag: ${{ steps.read.outputs.tag }}
    - name: Login to DockerHub
      uses: docker/login-action@v2
      if: ${{ steps.read.outputs.tag }} != 'main'
      with:
        username: ${{ secrets.DOCKERHUB_LOGIN }}
        password: ${{ secrets.DOCKERHUB_PASS }}
    - name: Build and push
      if: ${{ steps.read.outputs.tag }} != 'main'
      run: |
        docker buildx build \
          --platform linux/arm/v7 \ 
          --tag devkrolikowski/swiss-army-knife:${{ steps.read.outputs.tag }} \
          --file ./Dockerfile \ 
          --output type=image,push=true .